version: 2
updates:
  - package-ecosystem: maven
    directory: "/test"
    schedule:
      interval: monthly
    assignees:
      - "javiertuya" 
    open-pull-requests-limit: 20

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
    open-pull-requests-limit: 20
    assignees:
      - "javiertuya" 